version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./public:/project/public
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    networks:
    - bullet-train
  php:
    image: php:fpm
    volumes:
    - ./public:/project/public
    - ./vendor:/project/vendor
    - ./src:/project/src
    - ./conf:/project/conf
    - ./views:/project/views
    networks:
    - bullet-train

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bullettrain
    ports:
      - "5432:5432"
    networks:
    - bullet-train

  api:
    build:
      context: .
      dockerfile: docker/bullet-train-api/Dockerfile
    command: bash -c "cd /api/src
      && pipenv run python manage.py migrate --noinput
      && pipenv run python manage.py collectstatic --noinput
      && pipenv run gunicorn --bind 0.0.0.0:8000 -w 3 app.wsgi"
    environment:
      DJANGO_DB_NAME: bullettrain
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: password
      DJANGO_DB_PORT: 5432
      DJANGO_ALLOWED_HOSTS: db,php,api,api:8000
    ports:
      - "8081:8000"
    depends_on:
      - db
    networks:
    - bullet-train


  frontend:
    build:
      context: .
      dockerfile: docker/bullet-train-frontend/Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - api
    networks:
      - bullet-train

networks:
  bullet-train: