version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./public:/project/public
      - ./conf/site.conf:/etc/nginx/conf.d/site.conf
    links:
    - php
  php:
    image: php:7-fpm
    volumes:
    - ./public:/project/public
    - ./vendor:/project/vendor
    - ./src:/project/src
    - ./views:/project/views